### PR TITLE
New ko bundle

### PR DESCRIPTION
**Pull request by thebildeo**

### CODE REVIEW

**Comment by thebildeo** [comment]
Like this..?

**Comment by Slava0135** [comment]
I would prefer editing old file, not deleting it and making new one, but this will work.

**Comment by Slava0135** [comment]
(also make separate branch for each PR like you did first time)

**Comment by Slava0135** [comment]
You can edit file from github web interface

**Comment by Slava0135** [comment]
image
is there supposed to be new line?

**Comment by thebildeo** [comment]
no i didn't check 
Sorry

**Comment by Slava0135** [comment]
reset master branch, make new branch with fixes, do new PR (as you did first time)

**Pull request closed without merging**
